### ISSUE TITLE
No need to stringify/parse JSON

### ISSUE THREAD

**Issue by gmaughan** [natural-apptitude/ngrx-store-ionic-storage#1]
Just plugged your library into my Ionic 2 app. After sorting out my reducer composition, it worked first time. Very nice! I can now delete a bunch of Effects that were written to store slices of state.

A small suggestion: When using Ionic Storage I have not had to stringify/parse the stored data. Your code seems to stringify when storing and parse when retrieving. I don't think this is necessary.

Also makes for a better debugging experience as the Chrome debugging tools show an expandable object tree when the value is a JSON object rather than a string.

**Comment by joewoodhouse** [comment]
Hi Glenn,

Thanks very much for using this and glad you like it. Yea we found the same thing, basically all our Effects classes faded away once we didn't have to manage the storing of state.

I think you're right about the stringification/parsing, we're just doubling it up (I think this was a leftover relic from when we were using something else that didn't do the serialising itself). Would you be able to submit a PR?

**Comment by gmaughan** [comment]
pull request created. It's my first one! Hopefully it's ok. We are still in the dark ages using subversion in my organisation.

**Comment by fiznool** [comment]
Thanks! We published this as v2.0.0 since it is technically a breaking change (existing stringified data from v1 of the module won't be parsed into object format any more).

**Comment by pgcd** [comment]
Sorry to jump in on a closed issue but I think you should reintroduce the stringify/parse when running on IndexedDB/WebSQL (and I guess localstorage too).
At the moment, the result of running this in the browser (Chrome 57) can be:
`DOMException: Failed to execute 'put' on 'IDBObjectStore': function (number) {
        var b = number % 10,
            output = (~~(number % 100 / 10) === 1) ? 'th' :
  ...<omitted>... } could not be cloned.
    at http://localhost:8100/build/main.js:139736:29
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14529)
    at Object.onInvoke (http://localhost:8100/build/main.js:4425:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14469)
    at n.run (http://localhost:8100/build/polyfills.js:3:9741)
    at http://localhost:8100/build/polyfills.js:3:6774
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15213)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4416:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15134)
    at n.runTask (http://localhost:8100/build/polyfills.js:3:10390)
    at a (http://localhost:8100/build/polyfills.js:3:5313)
    at invoke (http://localhost:8100/build/polyfills.js:3:16210)
    at e (http://localhost:8100/build/polyfills.js:2:30854)`

(For context, this seems to happen when using MomentJS in the state, but I suppose it's not the only case)
