### ISSUE TITLE
confusing readme

### ISSUE THREAD

**Issue by yelhouti** [natural-apptitude/ngrx-store-ionic-storage#17]
This part of teh readme is pretty confusing
```
export const metaReducers: ActionReducer<any, any>[] = [storageMetaReducer];
...
StoreModule.forRoot(reducers, { metaReducers })
```
Since it puts an array inside an Object with no key which (by the way, I didn't know was valid js code and) is equivalent to `StoreModule.forRoot(reducers, metaReducers)` as far as my tests go
Am I missing something?
Also please correct:
`export const metaReducers: MetaReducer<any, any>[] = [storageMetaReducer];` **MetaReducer** as mentionned in another closed issue

**Comment by yelhouti** [comment]
Please close this issue when pull request #15 is merged

**Comment by joewoodhouse** [comment]
So `{ metaReducers }` is ES6 code for `{metaReducers: metaReducers}` (think the feature is called Enhanced Object Literals or something). So I wouldn't say it was equivalent to your example?

**Comment by yelhouti** [comment]
Thanks for the Info, I ll check the Store doc to see if there is a difference between the two syntax.
Thanks for merging the ReadMe, I'll reopen if needed
