### ISSUE TITLE
Sample project?

### ISSUE THREAD

**Issue by ehorodyski** [natural-apptitude/ngrx-store-ionic-storage#24]
I know this isn't a real issue, but is there any sample implementation project available to see a complete example of how to use this? I'm pretty new to using Redux with Ionic, but have many use-cases where it will make app state reliable.

**Comment by joewoodhouse** [comment]
I'm closing this as it isn't an issue with this library. I'd suggest looking at: https://github.com/ngrx/example-app

**Comment by ehorodyski** [comment]
I should have been more specific... I'd like an example of how to hydrate the store, it wasn't very easy to follow from the code snippets
