### ISSUE TITLE
Syncing feature

### ISSUE THREAD

**Issue by sneas** [natural-apptitude/ngrx-store-ionic-storage#26]
Hi,

First of all I want to thank you for such a nice library. We've successfully used it on one of our projects.

But I'm facing difficulty syncing the feature reducer. Unfortunately documentation says nothing about this.

Here is how I try to implement it for a feature in Ionic's page module:

```typescript
export function onSyncError(err) {
  console.log(err);
}
 
export const reducers: ActionReducerMap<appState> = {
  books: booksReducer,
  collection: collectionReducer
};
 
export const storageSyncReducer = storageSync({
  keys: ['collection'],   
  ignoreActions: [        
    BookActions.SELECT,
    CollectionActions.FILTER,
  ],
  hydratedStateKey: 'hydrated', 
  onSyncError: onSyncError      
});
 
export function storageMetaReducer(reducer: ActionReducer<any>): ActionReducer<any, any> {
  return storageSyncReducer(reducer);
}
 
export const metaReducers: MetaReducer<any, any>[] = [storageMetaReducer];
 
@NgModule({
  imports: [
    StoreModule.forFeature('feature', reducers, { metaReducers })
    EffectsModule.forFeature([ StorageSyncEffects ])
  ]
})
export class FeaturePageModule {}
```

The state does not get saved into storage and rehydrated.

I'm not sure whether I'm doing this right. Has anyone faced the same problem with a feature?

**Comment by sneas** [comment]
Sorry, my bad the lib doesn't work at all. Not only for the feature.

**Comment by akash-pal** [comment]
@sneas i am facing same issue, what was your solution?

**Comment by sneas** [comment]
@akash-pal we switched to `ngrx-store-localstorage`.
