### ISSUE TITLE
Data Loss if Adding SQLite?

### ISSUE THREAD

**Issue by ehorodyski** [natural-apptitude/ngrx-store-ionic-storage#29]
I have a legacy app that I'm very curious to start using state hydration. However, we don't include the SQLite plugin in our app -- we haven't for the 2 years it's been around. 

If that's a prerequisite to use `ngrx-store-ionic-storage`, would users lose their data that's being stored via the other storage drivers Ionic Storage provides?

**Comment by joewoodhouse** [comment]
This more just a question about Ionic Storage works, I'd suggest raising the question in their repository. I can't see why users would lose their data. From reading the readme of the Ionic Storage module, it looks like it will fallback to using whatever permanent storage is available.
