### ISSUE TITLE
INIT with ngrx 4

### ISSUE THREAD

**Issue by Biromain** [natural-apptitude/ngrx-store-ionic-storage#3]
Hi,
On a fresh ionic 3.5.3 project with ngrx/store, effects and ngrx-store-ionic-storage.

I get this error
`Cannot read property 'INIT' of undefined at storageSync`

It seem come from Dispatcher become not importable from `@ngrx/store`

Regards,

**Comment by joewoodhouse** [comment]
Ok yea they've made some changes in the latest version, so at the moment this is only going to work with ngrx 2

**Comment by biromain** [comment]
Yeah, thank.
It's configured with ngrx2 now.

Can you reply when update is available?

**Comment by joewoodhouse** [comment]
Sure will do.

**Comment by dfmartin** [comment]
I have put in PR #4  to address the @ngrx 4 issue.  However, I am not certain it will work with previous versions of @ngrx.  Note, there not only changes necessary to this code base but also to the developer's code in how they incorporate it into their own app.  I tried to put that into the readme, but let me know if it is clear

**Comment by biromain** [comment]
`Note, there not changes necessary to this code base`
That mean can i test it without use PR?

**Comment by dfmartin** [comment]
wow, I left out a single very important word.  Should read:
```Note, there are not *only* changes necessary to this code base```

My apologies.  I have updated

**Comment by biromain** [comment]
Don't worry
Seem clear, we just need to play with it in another way.
* [ActionReducer](https://github.com/ngrx/store/commit/19d9fe3f92bd57ffae541039109f6e6fcd686295#diff-6b8428f8e6a6dbdf122b035586b18631R5) seem in code from 2.0
* [ActionMapReducer](https://github.com/ngrx/platform/commit/224223a929dd155e418f57c249d82ff62d2ca060#diff-b34d6571dddfac50f11f2b9fd75f2b35R9) in code from 4.0 however used by developer's code.

I am not certain it will work with previous versions of @ngrx too, probably need to testing it.
But I do not see anything critical that will break the backward compatibility.

Edit: Misspel on [store](https://github.com/natural-apptitude/ngrx-store-ionic-storage/pull/4/files#diff-04c6e90faac2675aa89e2176d2eec7d8R7)

**Comment by joewoodhouse** [comment]
This should now be sorted with latest build?

**Comment by biromain** [comment]
It's fine. Thank 👍
