### ISSUE TITLE
Angular 9 compatibility

### ISSUE THREAD

**Issue by raymondboswel** [natural-apptitude/ngrx-store-ionic-storage#34]
After upgrading to angular 9 I get the following:

![image](https://user-images.githubusercontent.com/4745321/75129872-f3682b80-56d3-11ea-8d9e-d21cd3d261af.png)

I have forked the project and will try figure out what the fix is, but any assistance would be great.

**Comment by nosTa1337** [comment]
Same here.

[ng] ERROR in The given rootPath undefined is not a file of the program..../node_modules/ngrx-store-ionic-storage/dist/index.d.ts

**Comment by raymondboswel** [comment]
It's not a real solution, but the lib is pretty light weight, so I just copied the contents into my project. I ran into a bunch of other issues migrating to v9, so giving up for now.

**Comment by nosTa1337** [comment]
@raymondboswel I was also thinking about investigating but I will wait as well as I do not have the need to upgrade to v9. All the luck to those who are going with V9 already.

**Comment by BDominik** [comment]
Hi I'm also using the ngrx 9 and angular 9.
I really liked this package and worked fine with ionic 4 and older angular.
So for those who want elegant solution for this they can read this article.
https://medium.com/better-programming/sync-your-state-in-local-storage-with-ngrx-9d6ceba93fc0
I had to modify it to filter specific actions though.
Good luck with it.

**Comment by costafrancesco94** [comment]
I managed to made it work putting `"angularCompilerOptions": { "enableIvy": false }` as last line in the configuration object of my `tsconfig.app.json`. Don't really know what Ivi is, but it worked.
Solution suggested [from this issue](https://github.com/aws-amplify/amplify-js/issues/4681#issuecomment-584022782)

package.json
```
"@angular/common": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@capacitor/android": "^2.1.2",
    "@capacitor/core": "^2.4.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/storage": "^2.3.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^9.2.0",
    "@ngrx/store": "^9.2.0",
    "ngrx-store-ionic-storage": "^5.0.0",
```

**Comment by raymondboswel** [comment]
@costafrancesco94 As far as I understand, Ivy is one of the main new improvements made to the angular framework in version 9. So disabling it isn't ideal.

**Comment by JustDoItSascha** [comment]
`Error: The given rootPath undefined is not a file of the program.`

Is there any update on this? It still not works with Angular >9 and Ionic 5.

**Comment by raymondboswel** [comment]
@JustDoItSascha My previous comment offers a really simple solution: https://github.com/natural-apptitude/ngrx-store-ionic-storage/issues/34#issuecomment-590714118

**Comment by JustDoItSascha** [comment]
@raymondboswel Thank you, yeah I didn't see this and you're right, this was very easy! Now it runs with ionic 5 and angular 10 :)
