### ISSUE TITLE
Synchronized state not persisting to storage

### ISSUE THREAD

**Issue by rishadfb** [natural-apptitude/ngrx-store-ionic-storage#9]
**Operating System:** Manjaro Linux 17.0.6
**Kernel:** 4.9.59-1-MANJARO
**Node:** 8.8.1
**NPM:** 5.5.1
**Browser:** Chromium 62.0.3202.75
**Ionic CLI:** 3.16.0
**Angular:** 4.4.4
**ionic-angular**: 3.8.0
**ionic/storage:** 2.0.1
**ngrx/store:** 4.1.0
**ngrx/effects:** 4.1.0
**ngrx-store-ionic-storage:** 4.0.0
**zone.js:** 0.8.18

Before I took the screenshots below, I logged in to my application and created a new user session in my application which tracked some data. However, if I log out or refresh the page, I am unable to retrieve my stored state from storage for use in my application when I log in again. When I enable the hydration key, the hydration action shows the hydrate action run and the state data seems to be present, but if I refresh the app, the state is now empty. 

I don't know if this has anything to do with it, but local storage seems to be [managed differently](https://stackoverflow.com/questions/46325138/local-storage-with-chrome-61) in Chrome 61. However, I tested with the latest version of Ionic View on both Android and iOS and I have the same issue - the persisted session data is not restored.

I also tried downgrading to Angular 4.4.3 and ionic-angular 3.7.1, but there was no difference. 

Here is the code for my app reducers:

```
import * as Sessions from '../reducers/sessions';
import * as UiState from '../reducers/ui-state';

import { ActionReducer, ActionReducerMap, MetaReducer } from '@ngrx/store';

import { State } from '../../models/state';
import { storageSync } from 'ngrx-store-ionic-storage';

export function onSyncError(err) {
  console.log(err);
}

export const reducers: ActionReducerMap<State> = {
  sessions: Sessions.reducer,
  uiState: UiState.reducer
};

const storageSyncReducer = storageSync({
  keys: ['sessions'],             // Only sync the selected states
  ignoreActions: [],              // Don't sync when these actions occur
  onSyncError: onSyncError        // If a sync fails
});

export function storageMetaReducer(reducer: ActionReducer<any>): ActionReducer<any> {
  return storageSyncReducer(reducer);
}

export const metaReducers: MetaReducer<any>[] = [storageMetaReducer];
```

State before page refresh:
![01](https://user-images.githubusercontent.com/188425/32332618-917b049a-bfab-11e7-9602-dc34546a25c0.png)
Local storage before page refresh:
![01a](https://user-images.githubusercontent.com/188425/32333141-bbcbf60e-bfac-11e7-873e-ecf48d6d6ed7.png)
State after page refresh:
![02](https://user-images.githubusercontent.com/188425/32333827-6bc94d08-bfae-11e7-9efe-3ad41dc9bb6f.png)
Local storage after page refresh:
![02a](https://user-images.githubusercontent.com/188425/32333046-8a4573e4-bfac-11e7-81cd-f484bf29002a.png)

**Comment by rishadfb** [comment]
4.0.1 update fixes this issue. Thanks!

**Comment by joewoodhouse** [comment]
Huzzah!

**Comment by rishadfb** [comment]
**Operating System:** Manjaro Linux 17.1.4
**Kernel:** 4.14.16-1-MANJARO
**Node:** 9.5.0
**NPM:** 5.6.0
**Browser:** Chromium 64.0.3282.140
**Ionic CLI:** 3.19.1
**Angular:** 5.0.3
**ionic-angular:** 3.9.2
**ionic/storage:** 2.1.3
**ngrx/store:** 5.1.0
**ngrx/effects:** 5.1.0
**ngrx-store-ionic-storage:** 4.2.0
**zone.js:** 0.8.18

Getting the same issue again with my current setup.

**Comment by mwagena** [comment]
looks like i'm running into the same issue with the above specs..
After refresh the data still is available in my browser storage but not rehydrated to the redux store.

**Comment by rishadfb** [comment]
@joewoodhouse Is there a solution to this?

**Comment by shajeeck** [comment]
I am also getting this behavior, not on all devices, but when data stored started to increase some lower config phones started to show this behavior. When hydrated it loads an empty initial state

Any workarounds?

**Comment by shajeeck** [comment]
I did not find any issues after making sure i installed cordova sqlite plugin!
also i made local repo and edited index.js in dist 

`var storage = new storage_1.Storage({
  driverOrder: ['sqlite']
});`

warning: only work on cordova devices!!

 which will only take sqlite driver by ionic storage and added a ready() in fetchState() function to wait for storage to be ready. I cannot verify if this really helped but installing sqlite plugin helps make sure data is persistent and not cleaned by OS when stored in websql

**Comment by akash-pal** [comment]
@shajeeck did it work for you on the device/what about the browser? 

**Am using below configuration:** 
ionic-angular: 3.9.2
ngrx-store-ionic-storage:4.2.0
@ngrx/store:4.1.0
@ionic/storage:2.1.3

@rishadfb whats the status to this?

**Comment by shajeeck** [comment]
@akash-pal its working perfect for me with ionic 3 with no issues on browser and cordova devices.
I am using  @ngrx/store:6.1.0 with rxjs:6.2. and rxjs-compat:6.2.2 
Ionic 3 is still using angular 5, but ngrx 6 needs rxjs 6, thus installed rxjs-compat

**Comment by j2d2** [comment]
Ran into this same issue, with similar versions... it appears that if you allow the hydration to complete (Action: NSIS_APP_HYDRATED) before sending any new Actions it worked, but if you send action before the hydration is complete it does not. 
.. in case this helps somebody..
